version: '3.8'

services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile 
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    ports:
      - 80:80 
    depends_on:
      - web

  backend:
    build: ./backend
    ports:
      - 8081:8081
  